www:
  restart: always
  command: /usr/local/bin/gunicorn web.wsgi:application -w 2 -b :8000 --reload
  build: ./www
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  env_file: .env

redis:
  restart: always
  image: redis

celery:
  restart: always
  command: /usr/local/bin/celery -A web worker -l debug
  build: ./www
  volumes_from:
    - www
  links:
    - postgres:postgres
    - redis:redis
  env_file: .env

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
    - /www/media
  volumes_from:
    - www
  links:
    - www:www

postgres:
  restart: always
  image: postgres:9.5
  volumes_from:
    - data
  ports:
    - "5432:5432"

data:
  restart: always
  image: postgres:9.5
  volumes:
    - /var/lib/postgresql
  command: "true"
